version: '3.8'
services: 
    client: 
        stdin_open: true
        build: 
            context: ./client
        volumes: 
            - /client/node_modules
            - ./client:/client
        ports: 
            - "3000:3000"
    server:
        build: 
            context: ./server
        extra_hosts: 
            - "host.docker.internal:host-gateway"
        volumes: 
            - /server/node_modules
            - ./server:/server
        ports: 
            - "4000:4000"
        env_file: 
            - ./server/.env