version: '3.8'
services: 
    client: 
        stdin_open: true
        tty: true
        build: 
            context: ./client
            dockerfile: Dockerfile.dev
        volumes: 
            - /client/node_modules
            - ./client:/client
        ports: 
            - "3000:3000"
    server:
        build: 
            context: ./server
            dockerfile: Dockerfile.dev
        extra_hosts: 
            - "host.docker.internal:host-gateway"
        volumes: 
            - /server/node_modules
            - ./server:/server
        ports: 
            - "4000:4000"
        env_file: 
            - ./server/.env
    nginx:
        build: 
            context: ./nginx
            dockerfile: Dockerfile.dev
        depends_on: 
            - client
            - server
        restart: always
        ports: 
            - "5000:80"