FROM node:16.7-alpine

WORKDIR "/server"

COPY ./package.json .

COPY ./package-lock.json .

RUN npm install

RUN npm install -g sequelize-cli

COPY . .

EXPOSE 4000

COPY ./docker-entrypoint-dev.sh /docker-entrypoint-dev.sh

RUN chmod +x /docker-entrypoint-dev.sh

ENTRYPOINT ["/docker-entrypoint-dev.sh"]